CREATE TABLE CLIENT(
Client_id NUMBER(5) CONSTRAINT CLIENT_Client_id_pk PRIMARY KEY,
Client_name VARCHAR2(20) NOT NULL CONSTRAINT CLIENT_Client_name_uk UNIQUE,
Client_address VARCHAR2(30),
Client_city VARCHAR2(2) NOT NULL,
Client_prov CHAR(2) NOT NULL,
Client_Postal CHAR(2) NOT NULL
);

CREATE TABLE PROG(
Prog_id NUMBER(5) CONSTRAINT PROG_Prog_id_pk PRIMARY KEY,
Prog_name VARCHAR2(30) NOT NULL,
Prog_office CHAR(4) NOT NULL,
Prog_phone CHAR(10)
);

CREATE TABLE PROJECT(
Project_id NUMBER(6) CONSTRAINT PROJECT_Project_id_pk PRIMARY KEY,
Proj_name VARCHAR2(40) NOT NULL CONSTRAINT PROJECT_Proj_name_uk UNIQUE,
Complete_date DATE,
Total_cost NUMBER(8,2) CONSTRAINT PROJECT_Total_cost_ck 
                        CHECK (Total_cost > 0),
Client_id NUMBER(5) NOT NULL CONSTRAINT PROJECT_Client_id_fk REFERENCES CLIENT(Client_id)
);

CREATE TABLE PROJECT_STAFF(
Prog_id NUMBER(5),
Project_id NUMBER(6),
Week_Year CHAR(5),
Hours_worked NUMBER(4,1) NOT NULL,
CONSTRAINT PROJECT_STAFF_Prog_id_pk PRIMARY KEY,
CONSTRAINT PROJECT_STAFF_Prog_id_fk FOREIGN KEY (Prog_id) REFERENCES PROG(Prog_id),
CONSTRAINT PROJECT_STAFF_Project_id_pk PRIMARY KEY,
CONSTRAINT PROJECT_STAFF_Project_id_fk FOREIGN KEY (Project_id)  REFERENCES PROJECT(Project_id),
CONSTRAINT PROJECT_STAFF_Week_Year_pk PRIMARY KEY,
CONSTRAINT PROJECT_STAFF_Hours_worked_ck CHECK (Hours_work > 0)
);